import { Inter } from "next/font/google";
import "@picocss/pico";
import "material-icons/iconfont/material-icons.css";
import "./globals.css";

import Nav from "@/lib/components/nav/Nav";
import Fonts from "@/lib/components/Fonts";
import MoonSeo from "@/lib/components/MoonSEO";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Bloggyu",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="container">
                    <MoonSeo />
                    <Nav />
                    {children}
                    <p>© 2023 Hojun Lee. All Rights Reserved</p>
                </div>
            </body>
        </html>
    );
}
